import { Router } from 'express';
import { authenticate, authorize } from '../../middleware/auth.js';
import { validate } from '../../middleware/validate.js';
import { userController } from './user.controller.js';
import {
  accountStatusValidation,
  accountDeactivationValidation,
  comparisonValidation,
  listValidation,
  localLoginValidation,
  localRefreshValidation,
  localRegistrationValidation,
  localSessionIdValidation,
  passwordResetConfirmationValidation,
  passwordResetRequestValidation,
  profileValidation,
  publicUserValidation,
  roleValidation,
  savedListingValidation,
  targetUserValidation,
  verificationDecisionValidation,
  verificationFrameValidation,
  verificationRequirementsValidation,
  verificationSubmissionValidation,
} from './user.validation.js';

export const userRouter = Router();

userRouter.post(
  '/local-login',
  localLoginValidation,
  validate,
  userController.localLogin,
);
userRouter.post(
  '/local-register',
  localRegistrationValidation,
  validate,
  userController.localRegister,
);
userRouter.post(
  '/local-refresh',
  localRefreshValidation,
  validate,
  userController.localRefresh,
);
userRouter.post(
  '/local-logout',
  authenticate,
  userController.localLogout,
);
userRouter.post(
  '/local-password-reset/request',
  passwordResetRequestValidation,
  validate,
  userController.requestLocalPasswordReset,
);
userRouter.post(
  '/local-password-reset/confirm',
  passwordResetConfirmationValidation,
  validate,
  userController.confirmLocalPasswordReset,
);
userRouter.post('/session', authenticate, userController.startSession);
userRouter.get('/me', authenticate, userController.me);
userRouter.get('/me/sessions', authenticate, userController.localSessions);
userRouter.post(
  '/me/sessions/revoke-others',
  authenticate,
  userController.revokeOtherLocalSessions,
);
userRouter.delete(
  '/me/sessions/:sessionId',
  authenticate,
  localSessionIdValidation,
  validate,
  userController.revokeLocalSession,
);
userRouter.post(
  '/me/deactivate',
  authenticate,
  accountDeactivationValidation,
  validate,
  userController.deactivateMe,
);
userRouter.patch(
  '/me',
  authenticate,
  profileValidation,
  validate,
  userController.updateMe,
);
userRouter.patch(
  '/me/active-role',
  authenticate,
  roleValidation,
  validate,
  userController.selectRole,
);
userRouter.post(
  '/me/verification',
  authenticate,
  verificationSubmissionValidation,
  validate,
  userController.submitVerification,
);
userRouter.post(
  '/me/verification/scan-frame',
  authenticate,
  verificationFrameValidation,
  validate,
  userController.inspectVerificationFrame,
);
userRouter.get(
  '/me/verification/requirements',
  authenticate,
  verificationRequirementsValidation,
  validate,
  userController.verificationRequirements,
);
userRouter.post(
  '/me/blocked-users/:userId',
  authenticate,
  targetUserValidation,
  validate,
  userController.blockUser,
);
userRouter.delete(
  '/me/blocked-users/:userId',
  authenticate,
  targetUserValidation,
  validate,
  userController.unblockUser,
);
userRouter.get(
  '/me/saved-listings',
  authenticate,
  userController.savedListings,
);
userRouter.put(
  '/me/saved-listings/:listingId',
  authenticate,
  savedListingValidation,
  validate,
  userController.saveListing,
);
userRouter.delete(
  '/me/saved-listings/:listingId',
  authenticate,
  savedListingValidation,
  validate,
  userController.removeSavedListing,
);
userRouter.get('/me/comparison', authenticate, userController.comparison);
userRouter.put(
  '/me/comparison',
  authenticate,
  comparisonValidation,
  validate,
  userController.updateComparison,
);
userRouter.get(
  '/public/:id',
  publicUserValidation,
  validate,
  userController.publicProfile,
);
userRouter.get(
  '/',
  authenticate,
  authorize('admin'),
  listValidation,
  validate,
  userController.list,
);
userRouter.patch(
  '/:userId/verification',
  authenticate,
  authorize('admin'),
  verificationDecisionValidation,
  validate,
  userController.reviewVerification,
);
userRouter.patch(
  '/:id/status',
  authenticate,
  authorize('admin'),
  accountStatusValidation,
  validate,
  userController.changeAccountStatus,
);
